# Numpy kütüphanesinden Pytorch Kütüphanesine Dönüşüm

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.1.0'

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr.dtype

dtype('int32')

In [5]:
type(arr)

numpy.ndarray

In [7]:
torch_arr = torch.from_numpy(arr)

In [8]:
torch_arr

tensor([1, 2, 3, 4], dtype=torch.int32)

In [14]:
type(torch_arr)

torch.Tensor

In [10]:
torch_arr2 = torch.as_tensor(arr)

In [11]:
type(torch_arr2)

torch.Tensor

In [12]:
arr[0] = 999

In [13]:
torch_arr

tensor([999,   2,   3,   4], dtype=torch.int32)

Ana dizide yaptığımız değişiklikler ardından oluşturduğumuz torch dizilerine de etki ediyor. Eğer bunun oluşmasını istemiyorsak:

In [15]:
torch_arr3 = torch.tensor(arr)

In [16]:
torch_arr3

tensor([999,   2,   3,   4], dtype=torch.int32)

In [17]:
arr[0] = 8989

In [18]:
torch_arr

tensor([8989,    2,    3,    4], dtype=torch.int32)

In [19]:
torch_arr3

tensor([999,   2,   3,   4], dtype=torch.int32)

## Sonuç

numpy kütüphanesinden pytorch kütüphanesine dönüşüm için 3 yöntem vardır.
- 1. Yöntem: data = torch.from_numpy(array)
- 2. Yöntem: data = torch.as_tensor(array)
- 3. Yöntem: data = torch.tensor(array)