In [1]:
import numpy as np
import torch

In [2]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[4,5],[5,6],[8,9]])
c = torch.tensor([4,5,6])

In [3]:
c.pow(2)

tensor([16, 25, 36])

In [4]:
c+22

tensor([26, 27, 28])

In [5]:
c*2

tensor([ 8, 10, 12])

In [6]:
a.shape

torch.Size([2, 3])

In [7]:
b.shape

torch.Size([3, 2])

In [8]:
torch.mm(a,b)

tensor([[ 38,  44],
        [ 89, 104]])

In [9]:
a@b

tensor([[ 38,  44],
        [ 89, 104]])

In [10]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
len(a)

2

In [12]:
a.numel()

6