In [1]:
import torch

Uniform Dağılımlı

In [3]:
 torch.rand(4,3)

tensor([[0.9117, 0.7279, 0.7827],
        [0.7805, 0.7186, 0.3209],
        [0.7116, 0.0248, 0.4385],
        [0.8064, 0.0901, 0.9427]])

Normal Dağılımlı (standart sapması 1 ve ortalaması 0)

In [4]:
torch.randn(2,3)

tensor([[ 0.1262, -0.7286,  0.2502],
        [-1.6515,  0.8421,  0.8940]])

In [5]:
torch.randint(low=2, high=11, size=(5,5))

tensor([[10, 10, 10,  6,  8],
        [ 2,  3,  6,  7,  2],
        [ 7,  2,  4,  8,  5],
        [ 9,  4,  4, 10,  8],
        [ 4,  9,  5,  8,  6]])

In [6]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
x.shape

torch.Size([2, 5])

rand_like veya randn_like ile içine yazdığımız dizinin boyut özelliklerini alarak normal ve uniform dağılımlı matrisler oluşturur.

In [10]:
torch.rand_like(x)

tensor([[0.6567, 0.8603, 0.3309, 0.4493, 0.7320],
        [0.4081, 0.0552, 0.8622, 0.9406, 0.2673]])

In [9]:
torch.randn_like(x)

tensor([[ 0.3265, -0.0034, -1.0253,  1.9484,  0.2628],
        [ 0.7081,  1.0329, -0.5918, -0.6109,  1.0676]])

In [12]:
torch.randint_like(x, low = 2, high = 10)

tensor([[8., 9., 7., 9., 6.],
        [7., 8., 4., 2., 8.]])

In [38]:
torch.manual_seed(45)
a = torch.rand(5,2)
a

tensor([[0.1869, 0.9613],
        [0.6834, 0.8988],
        [0.0505, 0.5555],
        [0.7861, 0.0566],
        [0.7842, 0.1480]])

In [31]:
torch.rand(5,2)

tensor([[0.0388, 0.1037],
        [0.4216, 0.2373],
        [0.8111, 0.5340],
        [0.6834, 0.6528],
        [0.6123, 0.9834]])

In [39]:
a

tensor([[0.1869, 0.9613],
        [0.6834, 0.8988],
        [0.0505, 0.5555],
        [0.7861, 0.0566],
        [0.7842, 0.1480]])