In [1]:
import torch
import numpy as np

In [2]:
arr = np.array([1,5,6,7])

In [3]:
tarr = torch.tensor(arr)
tarr

tensor([1, 5, 6, 7], dtype=torch.int32)

In [4]:
tarr2 = torch.Tensor(arr)
tarr2

tensor([1., 5., 6., 7.])

Tensor u t ve T ile yazmak farklıdır. tensor = int, Tensor = float

In [5]:
tarr3 = torch.FloatTensor(arr)
tarr3

tensor([1., 5., 6., 7.])

son iki kod blogu aynı işlevi görüyor.

In [6]:
torch.empty(2,3)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.0065e-44]])

In [7]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.zeros(3,3,dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [9]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [11]:
torch.linspace(1,10,12)

tensor([ 1.0000,  1.8182,  2.6364,  3.4545,  4.2727,  5.0909,  5.9091,  6.7273,
         7.5455,  8.3636,  9.1818, 10.0000])

In [12]:
torch.linspace(1,10,12).reshape(4,3)

tensor([[ 1.0000,  1.8182,  2.6364],
        [ 3.4545,  4.2727,  5.0909],
        [ 5.9091,  6.7273,  7.5455],
        [ 8.3636,  9.1818, 10.0000]])

In [13]:
my_tensor = torch.tensor([5,6,7,6,5,4])

In [14]:
my_tensor.dtype

torch.int64

In [16]:
my_tensor.type(torch.float16)

tensor([5., 6., 7., 6., 5., 4.], dtype=torch.float16)