In [1]:
import numpy as np
import torch

In [9]:
a = torch.Tensor([1,2,3])
b = torch.Tensor([4,5,6])

In [3]:
a+b

tensor([5, 7, 9])

In [4]:
torch.add(a,b)

tensor([5, 7, 9])

In [7]:
torch.mul(a,b)

tensor([ 4, 10, 18])

In [10]:
torch.div(a,b)

tensor([0.2500, 0.4000, 0.5000])

In [11]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [12]:
a

tensor([ 4., 10., 18.])