In [1]:
import numpy as np
import torch

In [2]:
x= torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
x[1,1]

tensor(3)

In [5]:
x[:,1]

tensor([1, 3, 5])

In [6]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [7]:
#View
y = torch.arange(10)

In [8]:
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
z = y.view(5,2)

In [10]:
z

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
y[0] = 98989

In [13]:
z

tensor([[98989,     1],
        [    2,     3],
        [    4,     5],
        [    6,     7],
        [    8,     9]])

In [14]:
u = y.reshape(5,2)

In [15]:
u

tensor([[98989,     1],
        [    2,     3],
        [    4,     5],
        [    6,     7],
        [    8,     9]])

In [16]:
y[0] = 17

In [17]:
u

tensor([[17,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [18]:
y.view(5,-1)

tensor([[17,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [20]:
y.view(-1,5)

tensor([[17,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])